"""added coach model

Revision ID: 3abca4eb12fe
Revises: f049d53ef656
Create Date: 2024-01-07 22:48:53.709800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abca4eb12fe'
down_revision = 'f049d53ef656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coaches')
    # ### end Alembic commands ###
