"""added email and number for coach

Revision ID: 3d55fefe8d0d
Revises: bafc5353aa18
Create Date: 2024-01-16 20:37:33.247076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d55fefe8d0d'
down_revision = 'bafc5353aa18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('number')

    # ### end Alembic commands ###
